version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  user_birthday_web:
    build: user_birthday
    command: bash -c "python ./user_birthday/manage.py makemigrations api && python ./user_birthday/manage.py migrate && python ./user_birthday/manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
  letter_digit_web:
    build: letter_digit
    command: bash -c "python ./letter_digit/manage.py makemigrations api && python ./letter_digit/manage.py migrate && python ./letter_digit/manage.py runserver 0.0.0.0:8002"
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - db

